import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guideSidebar: [
    {
      type: 'category',
      label: 'Welcome',
      collapsed: false,
      items: [
        'intro/what-is-helix',
        'intro/why-helix',
        'intro/how-it-works',
        'intro/pick-your-path',
        'intro/meet-atlas',
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/install',
        'getting-started/your-first-world',
        'getting-started/your-first-script',
        'getting-started/publish-and-play',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: true,
      items: [
        'core-concepts/levels-and-maps',
        'core-concepts/actors',
        'core-concepts/components',
        'core-concepts/blueprints-101',
        'core-concepts/the-game-loop',
        'core-concepts/input-system',
        'core-concepts/coordinate-system',
        'core-concepts/assets-and-content',
      ],
    },
    {
      type: 'category',
      label: 'Scripting',
      collapsed: true,
      items: [
        'scripting/choosing-your-language',
        'scripting/blueprint-basics',
        'scripting/lua-basics',
        'scripting/js-basics',
        'scripting/packages',
        'scripting/events-system',
        'scripting/timers-and-delays',
        'scripting/debugging',
      ],
    },
    {
      type: 'category',
      label: 'Game Systems',
      collapsed: true,
      items: [
        'game-systems/characters',
        'game-systems/vehicles',
        'game-systems/weapons',
        'game-systems/inventory',
        'game-systems/user-interface',
        'game-systems/audio',
        'game-systems/world-building',
        'game-systems/database',
        'game-systems/economy',
      ],
    },
    {
      type: 'category',
      label: 'Multiplayer',
      collapsed: true,
      items: [
        'multiplayer/client-server-model',
        'multiplayer/replication',
        'multiplayer/remote-calls',
        'multiplayer/player-management',
        'multiplayer/syncing-state',
      ],
    },
    {
      type: 'category',
      label: 'Publishing',
      collapsed: true,
      items: [
        'publishing/the-vault',
        'publishing/instant-hosting',
        'publishing/monetization',
        'publishing/world-management',
      ],
    },
    {
      type: 'category',
      label: 'Migration Guides',
      collapsed: true,
      items: [
        'migration/from-fivem',
        'migration/from-roblox',
        'migration/from-ragemp',
      ],
    },
    {
      type: 'category',
      label: 'QBCore',
      collapsed: true,
      items: [
        'qbcore/overview',
        'qbcore/installation',
        'qbcore/player-guide',
        'qbcore/api',
        'qbcore/packages',
      ],
    },
    {
      type: 'category',
      label: 'Templates',
      collapsed: true,
      items: [
        'templates/starter-templates',
        'templates/roleplay-server',
        'templates/racing-game',
      ],
    },
    // ------------------------------------------------------------------
    // Roadmap + Changelog — linked from the top nav. Single-page entries
    // for now; we'll deepen them as we port content.
    // ------------------------------------------------------------------
    'roadmap',
    'changelog',
    // ------------------------------------------------------------------
    // Old Docs mirror — every page from docs.helixgame.com (MkDocs) that
    // doesn't yet have a natural home in the new IA lives here, preserving
    // the original hierarchy. Pages graduate OUT of this section as they
    // get rewritten into the sections above. See MERGE_PROJECT.md.
    // ------------------------------------------------------------------
    {
      type: 'category',
      label: 'Old Docs',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'old-docs'}],
    },
  ],
};

export default sidebars;
